version: '3.8'

services:
  dev:
    container_name: nestjs_api_dev_eshop
    image: nestjs-api-dev:1.0.0
    build:
      context: eshop-backend-nestjs
      target: development
      dockerfile: .eshop-backend-nestjs/Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
#  prod:
#    container_name: nestjs_api_prod_eshop
#    image: nestjs-api-prod:1.0.0
#    build:
#      context: .
#      target: production
#      dockerfile: ./Dockerfile
#    command: npm run start:prod
#    ports:
#      - 3000:3000
#      - 9229:9229
#    networks:
#      - nesjs-network
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    restart: unless-stopped



networks:
  nesjs-network:
